### ISSUE TITLE
Click to zoom on numbered lists and headings

### ISSUE THREAD

**Issue by jamie9090** [vslinko/obsidian-zoom#25]
Possible to add click to zoom for numbered lists too?

And any ideas if eventually we can have click to zoom on headings?

Sorry if this is the wrong place to post.

Thank you!

**Comment by vslinko** [comment]
@jamie9090 Hello, thank you for your feedback!

Numbered lists support was released in https://github.com/vslinko/obsidian-zoom/releases/tag/0.1.2
Could you please update the plugin and test it again?

Click to zoom on headers is not supported yet. I will convert your issue to a feature request.

**Comment by vslinko** [comment]
Oops, I missed that you meant click to zoom for numbered lists, not just support for numbered lists.
