### ISSUE TITLE
[BUG] [small] Not recognizing alternate header formats

### ISSUE THREAD

**Issue by b1uegh0st** [vslinko/obsidian-zoom#33]
**Describe the bug**
When I use h1 and h2 using the line syntax (`=====` and `-------`) the plugin don't consider it as header, so:
- Cannot zoom-in for those header.
- Header structure when zoomed-in is messed up (detect the wrong "parent", which for me the closest h3 which use `###`)

**Expected behavior**
All headers format are detected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: v0.12.19
 - Plugin Version: 0.1.2

**Additional context**
I use h1 and h2 format in that form to create some visual hints (of sections) in Edit mode. Not sure if other people use it much.

**Comment by vslinko** [comment]
@b1uegh0st thanks for your feedback.

Should be fixed in 0.2
