### ISSUE TITLE
Inserts line break rather than zooming in Live Preview mode [BUG]

### ISSUE THREAD

**Issue by rosewills** [vslinko/obsidian-zoom#34]
**Describe the bug**
In the new Live Preview mode, I can no longer zoom in on any section. If I click a bullet nothing happens; if I use the hotkey command, it just inserts a line break.

**To Reproduce**
1. Turn on Live Preview mode
2. Try clicking a bullet (does not zoom in)
3. Try using the "zoom in" command via hotkey (inserts linebreak instead)

**Expected behavior**
Both clicking the bullet and using the hotkey work fine with Live Preview turned off.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.13.2 (Insider Build)
 - Plugin Version: 0.1.2

I know Live Preview mode is still in active development, so I'll check if it still happens with future updates.
I love this plugin and rely on it daily- thanks for all the work you've put into it!

**Comment by vslinko** [comment]
@rosewills thank you for your feedback.

Should be fixed in 0.2
