### ISSUE TITLE
Strange typing behavior on Zoom in CM6

### ISSUE THREAD

**Issue by cansar** [vslinko/obsidian-zoom#39]
I love the updated Zoom plugin but have been running into some strange issues with letters appearing out of sequence when typing. The following minimal page seems to reproduce the issues. It can't get it to happen 100% of the time but it happens almost every time.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/92989/146588594-2d02b50b-a6fe-42fd-ba2e-190b8d91346e.png">

```
# H1 1 <Zoom into here, first>
<Start typing here>
# H1 2
```

Make sure there's a newline between the 2 sections. Create a new todo with CMD-Enter. The cursor jumps to the beginning of the line before the TODO. As you type the letters appear out of sequence, jumping towards the left of the word all of a sudden. If it doesn't happen the first time, zoom out and zoom back in.

I'm attaching a Loom of what happens: https://www.loom.com/share/6ac1b66cf4bb4ef0ac96bcacf58398a4

**Comment by vslinko** [comment]
@cansar Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.2.2
