### ISSUE TITLE
[BUG] Failing to Load on Mobile

### ISSUE THREAD

**Issue by iamrecursion** [vslinko/obsidian-zoom#42]
**Describe the bug**
When opening a vault on mobile, zoom fails to load.

**To Reproduce**
Open a vault where zoom is enabled.

**Expected behavior**
Zoom is either not available on mobile or works.

**Desktop (please complete the following information):**
 - OS: iOS
 - Obsidian Version: 1.0.5
 - Plugin Version: 0.2.1

**Additional context**
The error message (found using [Obsidian REPL](https://github.com/ktemkin/obsidian-repl)) is as follows:

```
TypeError: undefined is not an object (evaluating 'state.Facet')
```

**Comment by MisterY** [comment]
The same on Android. The plugin can be installed but not enabled. Enabling fails with an error message.

**Comment by MisterY** [comment]
Since there is #16, perhaps just mark as incompatible until it works?
