### ISSUE TITLE
[BUG] - Zoom functionality broken due to TypeError?

### ISSUE THREAD

**Issue by cweekly** [vslinko/obsidian-zoom#44]
**Description**
As of latest version (0.2.3), the Zoom hotkey (cmd+.) has no effect. 
Devtools shows a TypeError:

```
Command failed to execute:  obsidian-zoom:zoom-in
app.js:1 TypeError: Cannot read property 'main' of undefined
    at Object.editorCallback (eval at <anonymous> (app.js:1), <anonymous>:834:60)
    at Object.e.mobileOnly.xy.isMobile.e.checkCallback (app.js:1)
    at gO (app.js:1)
    at e.executeCommandById (app.js:1)
    at e.onTrigger (app.js:1)
    at e.handleKey (app.js:1)
    at e.onKeyEvent (app.js:1)
```

**To Reproduce**
1. Open any note with a list hierarchy
2. Put cursor focus on a nested item
3. Type zoom hotkey (ie CMD+.) 
4. Note nothing happens.
5. Check devtools, note the error.

**Expected behavior**
Zoom works as before (zoom in w CMD+. , zoom out w CMD+SHIFT+.)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.2
 - Obsidian Version: 0.13.12
 - Plugin Version: 0.2.3

**Additional context**
Tried with both legacy editor (my primary use case while I wait for Outliner to support Live Preview) and with Live Preview.

**Comment by vslinko** [comment]
@cweekly thanks for your feedback!

I don't know how that's possible, because it means your editor doesn't have a single cursor.
I can't reproduce this problem. Could you please send me the broken file and make a screen recording?

**Comment by cweekly** [comment]
Hi @vslinko, 
I don't understand what you mean about the editor not having a cursor. From a UX perspective it definitely has a "cursor" (ie, a blinking vertical line indicating the locus of control/input). 

> Could you please send me the broken file and make a screen recording?
It's not specific to any one file. And sorry, I can't make a screen recording, you're going to have to take my word for it. 

One more thing in case it helps: this is specific to my work machine (MacOS 11.6.2).
On my home machine (MacOS 10.15.7), with the exact same Obsidian and plugin versions, I can't reprod the issue.

**Comment by FelipeRearden** [comment]
> On my home machine (MacOS 10.15.7), with the exact same Obsidian and plugin versions, I can't reprod the issue.

It worked for Legacy Editor and Live Preview ? 

Because for me it only works in Live Preview :(

**Comment by cweekly** [comment]
On my home machine (MacOS 10.15.7), if I leave the legacy editor off, neither Zoom nor Outliner work at all. If I use the legacy editor, both Zoom and Outliner work as intended (other than this Outliner issue I filed on Monday: https://github.com/vslinko/obsidian-outliner/issues/230).

**Comment by FelipeRearden** [comment]
> On my home machine (MacOS 10.15.7), if I leave the legacy editor off, neither Zoom nor Outliner work at all. If I use the legacy editor, both Zoom and Outliner work as intended (other than this Outliner issue I filed on Monday: https://github.com/vslinko/obsidian-outliner/issues/230).

@cweekly I think this answer from @vslinko might help to understand the difference of behavior between your two computers

https://github.com/vslinko/obsidian-zoom/issues/46#issuecomment-1000824610

**Comment by vslinko** [comment]
I reproduced the issue with the "Use legacy editor" setting turned on.

Zoom plugin 0.2 does not support the legacy editor. But it should work with the "Use legacy editor" option turned off in both "Source Mode" and "Live Preview".

Could you update the plugin, disable "Use legacy editor" and check again?

If this does not help, please update Zoom plugin to version 0.2.6, enable "Debug Mode" in the plugin settings and copy logs from DevTools here.

**Comment by vslinko** [comment]
Closed due to inactivity. If you are still experiencing the problem, please create a new issue.
