### ISSUE TITLE
[BUG] View gets scrolled to top after zooming out instead of keeping active line on screen

### ISSUE THREAD

**Issue by ivan-liadniou-epam** [vslinko/obsidian-zoom#45]
When zooming out on a line in the middle of a long document (longer than screen height), the scroll position gets reset to the top of the document, and we lose track of the active line.

1. Open a document longer than screen height
2. Zoom in on a line at the end of the document, zoom out

**Expected behavior**
The line we zoomed out on stays in view.

 - OS: Windows
 - Obsidian Version: 0.13.13
 - Plugin Version: 0.2.3

**Comment by vslinko** [comment]
@ivan-liadniou-epam thank you for your feedback! Should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.2.4
