### ISSUE TITLE
[Bug] (0.2.4) Zoom in not Working in Legacy Editor (editor mode)

### ISSUE THREAD

**Issue by FelipeRearden** [vslinko/obsidian-zoom#46]
Hello @vslinko !!!!!

Just to let you know that Obsidian Zoom is not working when Legacy Editor is ON (previously Editor Mode from version 0.12.19)

For many Obsidian users that have old computers will keep using the now old Editor Mode because Live Preview is very slow for old computers and long notes.

I hope you could support Editor Mode for this new version of Obsidian Zoom. I would be extreme grateful to you :pray: :pray: :pray: 

Thanks for reading this!

I wish you a great day!!!!

**Comment by FelipeRearden** [comment]
Hello @vslinko !!!!

I made some tests to see if I find more information. 

There to actions to invoke Obsidian Zoom: Hotkey and Command Palette Modal:
- Zoom in
- Zoom out the entire document

What I saw is that we have different errors logs based on these two different inputs. Take a look

## Hotkey

Zoom in + Zoom out
![0](https://user-images.githubusercontent.com/85180696/147229292-64fc3625-f7a9-426c-a2e7-9a6e94e99170.png)


![1](https://user-images.githubusercontent.com/85180696/147229372-4ad52bcc-1375-42b7-bb0a-b82d54ea9d66.png)

## Command Palette

Zoom in
![2](https://user-images.githubusercontent.com/85180696/147229414-e57bb034-14c7-4c70-a984-1f87aef06183.png)

Zoom out
![3](https://user-images.githubusercontent.com/85180696/147229434-66cf5713-05a7-4ba4-8f3d-351b048c7b9c.png)


## Target Note

As you can see from the image above it´s just a simple note with one header and a line of text below.

```
# Header 1
lorem ipsim generator ate dkr r tkf f,m,,,rcmdeoeodl fewaxsercr fdeoskfmr foemjtgn fmeskx  
```

---

I hope you could reproduce this on your end :pray: 

Have a great day!

**Comment by vslinko** [comment]
@FelipeRearden thank you for your feedback.

Unfortunately, I will not support the legacy editor mode. But you can use a modern editor without a live preview feature.

<img width="932" alt="Screenshot 2021-12-24 at 15 36 09" src="https://user-images.githubusercontent.com/205823/147353254-a7a0a1d8-268b-4fd3-85c0-2800256be9be.png">

Also, I added a notice that legacy editor more is not supported, to make it clearer to everyone why the plugin does not work.

<img width="334" alt="Screenshot 2021-12-24 at 15 37 44" src="https://user-images.githubusercontent.com/205823/147353267-61777061-f3be-49e1-9810-b3a568228dc6.png">

**Comment by FelipeRearden** [comment]
> Unfortunately, I will not support the legacy editor mode. 

Thanks for your reply @vslinko 

> But you can use a modern editor without a live preview feature.

Thank you very much for this info. I didnt understood that we have this "new mode". Now its clear for me the option of two editor modes: Source Mode and Live Preview. 


> Also, I added a notice that legacy editor more is not supported, to make it clearer to everyone why the plugin does not work.

Great idea.
