### ISSUE TITLE
[BUG] The "zoom in" cursor is deviated from the bullet.

### ISSUE THREAD

**Issue by mzwlevi** [vslinko/obsidian-zoom#49]
**Describe the bug**
When move the cursor from the right to the bullet, the "zoom in" cursor is deviated from the bullet.

**To Reproduce**
1. Move the cursor from the right to the bullet.
2. See error

<img width="403" alt="Screen Shot 2021-12-29 at 22 30 47" src="https://user-images.githubusercontent.com/78029539/147673381-ba3ead57-0816-4497-b021-aa10090a7a2f.png">

**Expected behavior**
No matter which direction you move the cursor to the bullet, it can be displayed normally.

<img width="425" alt="Screen Shot 2021-12-29 at 22 31 47" src="https://user-images.githubusercontent.com/78029539/147673604-bdb59a6d-3566-48c8-93ab-c9a353571a2b.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Obsidian Version: 0.13.14
 - Plugin Version: 0.2.6

**Comment by vslinko** [comment]
@mzwlevi thank you for the feedback! should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.2.8

**Comment by mzwlevi** [comment]
> @mzwlevi thank you for the feedback! should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.2.8

Awesome! The "zoom" is so nice which can cooperate with "outliner".
