### ISSUE TITLE
Clicking a link to a heading should zoom in directly to that Heading.

### ISSUE THREAD

**Issue by kngautham** [vslinko/obsidian-zoom#51]
Great Plugin. Very excited to see that this plugin is coming soon to mobile. I have one suggestion.

When i click the link ta heading, is it possible to zoom in directly to that heading. 

That would be very awesome

**Comment by vslinko** [comment]
@kngautham thank you for your feedback!

Clicking on headings already mentioned in the discussions.
Please follow https://github.com/vslinko/obsidian-zoom/discussions/30
Closing this issue as a duplicate.
