### ISSUE TITLE
Add support for the mobile app

### ISSUE THREAD

**Issue by vslinko** [vslinko/obsidian-zoom#52]
ref https://github.com/vslinko/obsidian-zoom/discussions/16

**Comment by StefanoRausch** [comment]
I support this request.

**Comment by FelipeRearden** [comment]
Hello @vslinko 

I did some investigation about support on Mobile that could help to solve this issue 🙏

My comment can be read here → https://github.com/vslinko/obsidian-zoom/discussions/16#discussioncomment-3286790


I hope you could bring support on mobile 🙏🙏🙏


I wish you a fantastic day!

**Comment by Fyzu** [comment]
Implemented in #78
