### ISSUE TITLE
[BUG] Asks to enable Folding even though they're already enabled

### ISSUE THREAD

**Issue by Lulullia** [vslinko/obsidian-zoom#63]
**Describe the bug**
When zooming in (through command or clicking on bullet), it doesn't work and instead shows a notice saying that I should enable Fold Heading and Fold Indent. Both options are already enabled in my settings. Tried reloading, issue still persists.

**To Reproduce**
1. Enable Fold Heading and Fold Indent.
2. Use Zoom command on a list item.
3. Nothing happens, a notice appears saying I need to enable Fold options.

**Expected behavior**
Since required options are enabled, everything should work normally

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.14.6
 - Plugin Version: 0.2.8

**EDIT**
I just realized the issue also happens with the Outliner plugin -- when I use the command to fold/unfold a list item, a notice saying that I need to enable folding appears.
Could it be that it is conflicting with another plugin?

**Comment by Lulullia** [comment]
Sorry for the late reply, here's an archive of my vault. I tested the issue in it and it still isn't working (there's a sample note with a list in it).
[Archive.zip](https://github.com/vslinko/obsidian-zoom/files/8599854/Archive.zip)

**Comment by pitibalrog** [comment]
Hi,

Just to say I've the same issue with Zoom and Outliner, but my workaround is to disable then enable again Fold Heading and Fold Indent. After this manipulation I don't have this problem any more.

I've juste done some test with a new vault dedicated to test this bug with only zoom and outliner community plugins and I've the same behaviour.

Here are the same vault before workaround [BugZoom-KO.zip](https://github.com/vslinko/obsidian-zoom/files/8609671/BugZoom-KO.zip) and after workaround [BugZoom-OK.zip](https://github.com/vslinko/obsidian-zoom/files/8609672/BugZoom-OK.zip). 

I hope it will help you to find the cause by searching differences between the two vaults.

My config :
- Win 11
- Obsidian 0.14.6
- Zoom 0.2.8
- Outliner 2.2.5

**Comment by Lulullia** [comment]
Thanks for the workaround @pitibalrog ! It works for me.

**Comment by vslinko** [comment]
Thank you all for the feedback!
Should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.3.0
