### ISSUE TITLE
Zoom Out Not Working (shift+cmd+.)

### ISSUE THREAD

**Issue by tillmanjex** [vslinko/obsidian-zoom#66]
**Describe the bug**
Zoom out fully does not work. Most likely because of German keyboard.

**To Reproduce**
1. Zoom in to any level in a list with `cmd+.`
2. Press `shift+cmd+.`

**Expected behavior**
I expect to zoom back out fully to the whole page

**Screenshots**

**Desktop (pleasecomplete the following information):**
 - OS: MacOS 12.0.1
 - Obsidian Version: 0.15.6
 - Plugin Version: 0.2.8

**additional information**
I am using a german keyboard. 
the period `.` and colon `:` are on the same key.

**Comment by vslinko** [comment]
@tillmanjex thank you for the feedback!
Should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.3.0

**Comment by tillmanjex** [comment]
@vslinko updated, but `cmd+shift+.` (ie zoom out fully) does not work.
I tried both keypress sequences: `cmd->shift->.`  and `shift->cmd->.`
