### ISSUE TITLE
remove manifest-beta.json

### ISSUE THREAD

**Issue by TfTHacker** [vslinko/obsidian-zoom#74]
I really appreciate your plugins, thank you for all your good work.

if you are not longer testing with brat, you should remove manifest-beta.json. BRAT users will not get your updates unless you update manifest-beta.json.

So either remove the beta file, or update its internal version number for your plugin. 

Tnx!

**Comment by vslinko** [comment]
@TfTHacker thank you for the feedback! I removed manifest-beta.json
