### ISSUE TITLE
[BUG] Right after zooming in, scrolling is janky

### ISSUE THREAD

**Issue by SkepticMystic** [vslinko/obsidian-zoom#9]
**Describe the bug**

Immediately after zooming in on a heading, if I start scrolling (up or down), the view keeps jumping back to the line it started on. I have to scroll for a few seconds before it gets "unstuck", and starts working normally again.

**To Reproduce**

1. Zoom in on a heading
2.  Start scrolling
3. The view should keep jumping back, not letting you scroll for a few seconds

**Expected behavior**

It shouldn't get stuck when scrolling

**Screenshots**

Here is a gif of me scrolling **up** the entire time, but see how the line numbers keep jumping back
![](https://imgur.com/UddFy8p.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.12.4 (Insider)
 - Plugin Version: 0.1.1

**Comment by gavinmn** [comment]
I'm experiencing this too on:
- macOS: 11.4
- Obsidian: 0.12.15 Insider
- Plugin: 0.1.2

Let me know if I can provide any other info that would help debug.

**Comment by FelipeRearden** [comment]
Hello @SkepticMystic !!!!!

Just to let you know that I think version `0.2.5` Solves this problem :)

I tried to reproduce in my end and I didnt feel janky :)

Always good to talk to you !!!
Happy Holidays !!!!

**Comment by vslinko** [comment]
@SkepticMystic thank you for your feedback. Could you try to reproduce the issue with latests versions of Obsidian and Zoom plugin?

**Comment by vslinko** [comment]
Closed due to inactivity. If you are still experiencing the problem, please create a new issue.
